"""Initial migration

Revision ID: 8c43fc085050
Revises: 
Create Date: 2025-10-16 12:45:06.977936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c43fc085050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('qcc_industry', schema=None) as batch_op:
        batch_op.drop_column('taxpayer_qualification')
        batch_op.drop_column('establishment_date')
        batch_op.drop_column('insured_headcount')
        batch_op.drop_column('sci_tech_rating')
        batch_op.drop_column('city')
        batch_op.drop_column('is_micro_small_enterprise')
        batch_op.drop_column('qcc_industry_category_medium')
        batch_op.drop_column('qcc_industry_category_minor')
        batch_op.drop_column('district')
        batch_op.drop_column('registration_authority')
        batch_op.drop_column('taxpayer_identification_number')
        batch_op.drop_column('address')
        batch_op.drop_column('registered_capital')
        batch_op.drop_column('qcc_score')
        batch_op.drop_column('national_standard_industry_category_medium')
        batch_op.drop_column('business_term')
        batch_op.drop_column('paid_in_capital')
        batch_op.drop_column('latest_annual_report_revenue')
        batch_op.drop_column('insured_headcount_annual_report_year')
        batch_op.drop_column('registration_status')
        batch_op.drop_column('unified_social_credit_code')
        batch_op.drop_column('province')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('national_standard_industry_category_minor')
        batch_op.drop_column('sci_tech_score')
        batch_op.drop_column('credit_rating')

    with op.batch_alter_table('qcc_tech', schema=None) as batch_op:
        batch_op.drop_column('valid_from')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('issuing_authority')
        batch_op.drop_column('valid_to')
        batch_op.drop_column('number')
        batch_op.drop_column('certification_year')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qcc_tech', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('certification_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('valid_to', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('issuing_authority', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.DATE(), nullable=True))

    with op.batch_alter_table('qcc_industry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_rating', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sci_tech_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('national_standard_industry_category_minor', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('unified_social_credit_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('insured_headcount_annual_report_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('latest_annual_report_revenue', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid_in_capital', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_term', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('national_standard_industry_category_medium', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('qcc_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('registered_capital', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('taxpayer_identification_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_authority', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('qcc_industry_category_minor', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('qcc_industry_category_medium', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_micro_small_enterprise', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sci_tech_rating', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('insured_headcount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('establishment_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('taxpayer_qualification', sa.VARCHAR(length=100), nullable=True))

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)

    # ### end Alembic commands ###
