"""initial_schema

Revision ID: f20c4a9f4b46
Revises: 
Create Date: 2026-03-23 12:48:28.264250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20c4a9f4b46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enterprise_size', sa.String(), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('enterprise_type', sa.String(), nullable=True),
    sa.Column('industry_main', sa.String(), nullable=True),
    sa.Column('industry_major', sa.String(), nullable=True),
    sa.Column('is_high_tech', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('business_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('guarantee_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('loan_start_date', sa.Date(), nullable=True),
    sa.Column('loan_due_date', sa.Date(), nullable=True),
    sa.Column('loan_interest_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('guarantee_fee_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('outstanding_loan_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('outstanding_guarantee_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('loan_status', sa.String(length=50), nullable=True),
    sa.Column('cooperative_bank', sa.String(length=100), nullable=True),
    sa.Column('snapshot_year', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_data_id'), 'business_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_data_id'), table_name='business_data')
    op.drop_table('business_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
